---
title: "SNA_S21_activism"
author: "Paul Antwerpes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(igraph)
# Setup-Chunk 
  # Daten einlesen
edges <- read.csv("https://raw.githubusercontent.com/Pa025/Netzwerk-Aktivismus-Pa0225/main/Netzwerk_Aktivistisch_Antwerpes%20-%20Edgelist%20(2).csv", header=T, as.is=T, sep = ",")
nodes <- read.csv("https://raw.githubusercontent.com/Pa025/Netzwerk-Aktivismus-Pa0225/main/Netzwerk_Aktivistisch_Antwerpes%20-%20Nodelist%20(1).csv", header=T, as.is=T, sep = ",")

  # edgematrix erstellen
edgematrix <- as.matrix(edges)

  # igraph-Objekt erstellen
activists <- graph_from_data_frame(d=edgematrix, vertices=nodes, directed = F)

activists
```

```{r Visualisierung, fig.height=9, fig.width=16}
# Organisationen und Personen entsprechend kenntlich machen (two-mode-network); Zusatz: nach Parteien einfärben



V(activists)[V(activists)$type == 1]$shape <- "circle"

V(activists)[V(activists)$type == 2]$shape <- "square" 




  
  # nachfolgender Befehl errechnet den degreewert aller nodes in einen neuen datensatz "degree_option", dadurch kann man im plot Befehl dann die Größe der Nodes abhängig von ihrem degreewert machen!

degree_option <- degree(activists, mode="all")

plot(activists,
     set.seed=12,
     asp=0, 
     layout=layout_with_kk,
     edge.arrow.size=.3,
     vertex.size = 2,
     vertex.label.cex=0.5,
     vertex.size = degree_option*0.5,
     vertex.label.cex=1,
     main = "Netzwerk der beteiligten Personen und Organisationen und deren Beziehungen zum Bauprojekt Stuttgart 21",
     sub = "Die Größe der Knoten ist abhängig von ihren jeweiligen Degreewerten — Datenerhebung erfolgte durch Louis G, Sinan K, Mia M, David V, Paul A")
```

```{r Erste Untersuchungen}

count_components(activists)
  # Das Netzwerk activists hat genau eine Komponente.

edge_density(activists)
  # Das Netzwerk SNA_S21 hat eine Kantendichte von etwa 11,9 %

cl_sna <- cluster_walktrap(activists)

  # Cluster-Analyse der einzelnen Cluster des Netzwerks SNA_S21 (Cluster-Walktrap-Analyse)
plot(cl_sna,
     activists,
     main = "Cluster-Walktrap Analyse des Netzwerks SNA_S21",
     set.seed=12,
     asp=0, 
     layout=layout_with_kk,
     edge.arrow.size=.3,
     vertex.size = 2,
     vertex.label.cex=0.5)

  # Degree-Berechnungen aller Edges eines Nodes (?)
sna_deg <- degree(activists, mode = "total")
which.max(sna_deg)
  # Den höchsten Degreewert besitzt Klaus Gebhardt mit 19.

  # Betweenness-Berechnungen
sna_betw <- betweenness(activists, directed = F, normalized = T)
which.max(betweenness(activists))
  # Hier ist das Klaus Riedel der Node mit dem höchsten Betweenness-Wert.

  # Closeness-Berechnung
sna_close <- closeness(activists)
which.max(closeness(activists))
  #Der Node mit dem höchsten Closeness-Wert ist Nisha Toussaint.

  # Eigenvector-Zentralitäts-Berechnung
sna_eigenvec <- eigen_centrality(activists)
sna_eigenvec_new <- sna_eigenvec$vector
#0.0732
  

  # Erstellung eines Dyaden-Zensus.
dyad_census(activists)
  # Es gibt 141 mutual Verbindungen im Netzwerk activsts 

  # Reziprozitäts-Berechnung
reciprocity(activists, mode = "ratio")
  # Da es sich beim Netzwerk um ein ungerichtetes Netzwerk handelt kann die Reziprozität nicht verlässlich festgestellt werden. Sie beträgt hier genau 1.
```
```{r fig.height=9, fig.width=16}

#Teilnetzwerke erstellen

force <- subgraph.edges(activists, E(activists)[weight==2])
force 

plot(force,
     main = "Aktivisten",
     set.seed=12,
     asp=0, 
     layout=layout_with_kk,
     edge.arrow.size=.3,
     vertex.size = 2,
     vertex.label.cex=0.5)

# Ego-Netzwerk 

Schutzgemeinschaft_Filder_Ego <- make_ego_graph(activists, order = 2, nodes = V(activists)$name == "Schutzgemeinschaft Filder")

Schutzgemeinschaft_Filder_Ego1 <- Schutzgemeinschaft_Filder_Ego[[1]]

plot(Schutzgemeinschaft_Filder_Ego1,
     main="Ego-Netzwerk Knoten 7, erster Grad",
     edge.color="grey80",
     edge.arrow.size=.3,
     vertex.size=5)
```
```{r}
#Parteien einfärben

V(activists)[V(activists)$party == "SPD"]$color <- "darkred"
V(activists)[V(activists)$party == "Linke"]$color <- "red"

plot(activists,
     set.seed=12,
     asp=0, 
     layout=layout_with_kk,
     edge.arrow.size=.3,
     vertex.size = 2,
     vertex.label.cex=0.5)
```
